version: '3'

services:
  #The reverse proxy service (Træfik)
  reverse-proxy:
    image: traefik #The official Traefik docker image
    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    ports:
      - "8081:80"     #The HTTP port
      - "8080:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
  transmission:
    image: linuxserver/transmission
    restart: always
    ports:
      - "9000:9091"
      - "59000:51413"
      - "59000:51413/udp"
    volumes:
      - "./data:/var/lib/transmission-daemon/info"
      - "./complete:/var/lib/transmission-daemon/downloads"
      - "./downloading:/var/lib/transmission-daemon/downloading"
      - "./incomplete:/var/lib/transmission-daemon/incomplete"
    resources:
    limits:
    memory:800
    labels:
      - "traefik.frontend.rule=Host:transmission.docker.localhost"



